version: "3"
services:
  i3t:
    container_name: it_tells_the_time_package
    image: node:20.9.0-alpine3.18
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 5173:5173
    command: >
      sh -c "npm install && npm run dev"
    restart: always
